### PR TITLE
added ferment logo

### PR DESCRIPTION
**Pull request by kwijibo**

### CODE REVIEW

**Comment by clehner** [comment]
it's a little big...
2017-03-22-133649_688x611_scrot
perhaps there is a screenshot that could be cropped to 250x150?

**Comment by clehner** [comment]
adding one... 
2017-03-22-174310_270x329_scrot
but the text overflows. @kwijibo okay to remove the second sentence "Like SoundCloud but decentralized." to make it fit better? the screenshot may be able to give the suggestion that it is an alternative to soundcloud.

thanks for prompting us to keep these things updated

**Comment by kwijibo** [comment]
@clehner sure - sorry I should have checked the size was OK before submitting the PR

**Comment by clehner** [comment]
no problem :)

**Pull request closed without merging**
